GET http://localhost:4004/odata/v4/nomination-services/CreateSPSet('40000787')?$expand=toHeaderTable,toservpara,toClausecode,toCustfld,toOrgDetail
###
GET http://localhost:4004/odata/v4/nomination-services/getNominationsByCustomer?SoldToParty='1100000003'


####
GET http://localhost:4004/odata/v4/nomination-services/getContractsByCustomerNDocType?SoldToParty='1100000003'&DocTyp='ZGTA'



###

GET http://localhost:4004/odata/v4/nomination-services/getContractDetailsAndPastNom?DocNo='40000932'

####
GET http://localhost:4004/odata/v4/nomination-services/getContractMatDetailsByGasday?DocNo='40000942'&Gasday=2025-03-15



###
GET http://localhost:4004/odata/v4/nomination-services/ZNOMMASTER8?$filter=Customer eq '1100000003'&$expand=to_contract($filter=DocType eq 'S' and Vbeln eq '40000740')

###
GET http://localhost:4004/odata/v4/nomination-services/getContractByCustomer?Customer=11000000033

###

POST  http://localhost:4004/odata/v4/nomination-services/znom_headSet
Content-Type: application/json


###
GET http://localhost:4004/odata/v4/nomination-services/getContractDetailsAndPastNom?DocNo=40000941

####
GET http://localhost:4004/odata/v4/nomination-services/getContractDetail?DocNo='40001065'&Material='2000000068'&Redelivery_Point='C1100003'


####

GET http://localhost:4004/odata/v4/nomination-services/getPastNominationdata?DocNo='40001070'&Material='2000000068'

###

GET http://localhost:4004/odata/v4/nomination-services/getMinMaxDCQByGasDate?DocNo='40001065'&Material='2000000068'&Redelivery_Point='C1100003'&Gasday=2025-04-16

####
GET http://localhost:4004/odata/v4/nomination-services/VirtualNominations
#######

GET http://localhost:4004/odata/v4/nomination-services/getRenominationContractData?DocNo='40001042'&Material='2000000068'&Redelivery_Point='C1100003'&Gasday=2025-04-17

####
GET http://localhost:4004/odata/v4/nomination-services/getRenominationContractData?DocNo='40001042'&Material='2000000068'&Redelivery_Point='C1100003'&Gasday=2025-04-30


####\
GET http://localhost:4004/odata/v4/nomination-services/nomi_SaveSet(Gasday='2025-03-24',Vbeln='40000945')

###
GET http://localhost:4004/odata/v4/nomination-services/nomi_SaveSet?$filter=Gasday eq '2025-03-31'&Vbeln eq '40000945'
 

#####
GET http://localhost:4004/odata/v4/nomination-services/xGMSxFETCHNOMINATION?$filter=DocNo eq '4600000374'









####

####
# PUT http://localhost:4004/odata/v4/nomination-services/nomi_SaveSet(Gasday='2025-03-17',Vbeln='40000942')
# Content-Type: application/json

# {
#         "Gasday" : "2025-03-17",
#         "Vbeln" : "40000942",
#         "ItemNo" : "000010",
#         "NomItem" : "10",
#         "DeliveryPoint" : "",
#         "RedelivryPoint" : "C1100003",
#         "ValidTo" : "04:00:00",
#         "ValidFrom" : "04:00:00",
#         "Material" : "2000000068",
#         "Timestamp" : null,
#         "Nomtk" : "",
#         "Kunnr" : "",
#         "Auart" : "",
#         "Ddcq" : "0.000",
#         "Rdcq" : "0.000",
#         "Uom1" : "MBT",
#         "Pdnq" : "0.000",
#         "Event" : "",
#         "Adnq" : "0.000",
#         "Rpdnq" : "2600.000",
#         "Znomtk" : "",
#         "Src" : "",
#         "Remarks" : "",
#         "Flag" : "",
#         "Action" : "",
#         "Path" : "",
#         "CustGrp" : "",
#         "SrvProfile" : ""
#       }
####
PUT http://localhost:4004/odata/v4/nomination-services/nomi_SaveSet(Gasday='2025-03-24',Vbeln='40000945')
Content-Type: application/json

{
  "Gasday": "2025-03-24",
  "Vbeln": "40000945",
  "ItemNo": "000010",
  "NomItem": "0000000010",
  "DeliveryPoint": "AMRELI",
  "RedelivryPoint": "",
  "ValidTo": "10:04:00",
  "ValidFrom": "06:04:00",
  "Material": "2000000068",
  "Timestamp": null,
  "Nomtk": "",
  "Kunnr": "",
  "Auart": "",
  "Ddcq": "2000.000",
  "Rdcq": "0.000",
  "Uom1": "MBT",
  "Pdnq" : "2200.000",
  "Event": "No-event",
  "Adnq": "0.000",
  "Rpdnq": "0.000",
  "Znomtk": "",
  "Src": "",
  "Remarks": "",
  "Flag": "",
  "Action": "",
  "Path": "",
  "CustGrp": "",
  "SrvProfile": ""
}


####
POST http://localhost:4004/odata/v4/nomination-services/updateNomination
Content-Type: application/json

{
  "Gasday": "2025-03-24",
  "Vbeln": "40000945",
  "ItemNo": "000010",
  "NomItem": "0000000010",
  "DeliveryPoint": "AMRELI",
  "RedelivryPoint": "",
  "ValidTo": "10:04:00",
  "ValidFrom": "07:04:00",
  "Material": "2000000068",
  "Timestamp": null,
  "Nomtk": "",
  "Kunnr": "",
  "Auart": "",
  "Ddcq": "2000.000",
  "Rdcq": "0.000",
  "Uom1": "MBT",
  "Pdnq" : "2000.000",
  "Event": "No-event",
  "Adnq": "0.000",
  "Rpdnq": "0.000",
  "Znomtk": "",
  "Src": "",
  "Remarks": "",
  "Flag": "",
  "Action": "",
  "Path": "",
  "CustGrp": "",
  "SrvProfile": ""
}




####
GET http://localhost:4004/odata/v4/odataservices/ZNOMCPDATA?$filter=Gasday eq 2025-02-10&vbeln eq '40000797'


#####

POST http://localhost:4004/odata/v4/nomination-services/znom_headSet
Content-Type: application/json


# {
# "Gasday" : "2025-02-26",
#  "Vbeln" : "40000796",
# "nomi_toitem":
# [
# {
#         "Gasday" : "2025-02-26",
#         "Vbeln" : "40000796",
#         "ItemNo" : "000020",
#         "NomItem" : "10",
#         "Versn" : "",
#         "DeliveryPoint" : "",
#         "RedelivryPoint" : "C1100003",
#         "ValidTo" : "06:40:00",
#         "ValidFrom" : "06:30:00",
#         "Material" : "2000000068",
#         "Kunnr" : "",
#         "Auart" : "ZGSA",
#         "Ddcq" : "0.000",
#         "Rdcq" : "0.000",
#         "Uom1" : "MBT",
#         "Pdnq" : "2500.000",
#         "Event" : ""
#       }
# ]

# }


####
POST http://localhost:4004/odata/v4/nomination-services/handleSystemNomination
Content-Type: application/json

{}


####
POST http://localhost:4004/odata/v4/nomination-services/znom_headSet
Content-Type: application/json

{
  "Gasday": "2025-04-03",
  "Vbeln": "40000945",
  "nomi_toitem": [
    {
      "Contracttype":"S",
      "Source":"Manual",
      "Gasday": "2025-04-03",
      "Vbeln": "4600000374",
      "ItemNo": "10",
      "NomItem": "20",
      "Versn": "",
      "DeliveryPoint": "AMRELI",
      "RedelivryPoint": "",
      "ValidTo": "06:00:00",
      "ValidFrom": "06:00:00",
      "Material": "2000000068",
      "Kunnr": "",
      "Auart": "ZGTA",
      "Ddcq": "2000.000",
      "Rdcq": "0.000",
      "Uom1": "MBT",
      "Event": "No-event",
      "Adnq": "0.000",
      "Pdnq": "2000",
      "Znomtk": "",
      "Src": "",
      "Remarks": "",
      "Flag": "",
      "Action": "",
      "Path": "",
      "CustGrp": "",
      "SrvProfile": ""
    }
  ]
}


##########
POST http://localhost:4004/odata/v4/nomination-services/Nom_DetailSet
Content-Type: application/json

{
"Vbeln": "40001042",
"Redelivrypoint": "C1100003",
"ValidFrom": "2025-04-01",
"ValidTo": "2025-04-05",
"SoldToParty": "1100000003",
"Material": "2000000068",
"DpDnq": "4500.000",
"Uom": "MBT",
"RpDnq": "5000.000",
"DeliveryPoint": "DAHEJ",
"Event": "No-event"
}








